pub mod envelope;
pub mod error;
pub mod health_poller;
pub mod instance_manager;
pub mod registry;
pub mod registry_server;
pub mod registry_store;
pub mod supervisor;
pub mod transport;
pub mod types;
pub mod workflow;

pub use envelope::{read_envelope, write_envelope, Envelope, EnvelopeKind};
pub use error::{AetherError, Outcome};
pub use instance_manager::InstanceManager;
pub use registry::AgentRegistry;
pub use supervisor::{Supervisor, SupervisorEvent};
pub use transport::{AgentFactory, Transport};
pub use transport::{HttpAgentFactory, HttpTransport};
pub use types::{AgentNode, FailurePolicy, HealthStatus, SpawnPolicy};
pub use workflow::{Edge, EdgePredicate, Workflow, WorkflowBuilder};
